# Generated by Django 4.2.30 on 2026-08-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
